### ISSUE TITLE
Consider adding a suffix to register dump file

### ISSUE THREAD

**Issue by bruno-f-cruz** [SainsburyWellcomeCentre/aeon_acquisition#101]
When using  [LogHarpState](https://github.com/SainsburyWellcomeCentre/aeon_acquisition/blob/main/src/Aeon.Acquisition/LogHarpState.bonsai) a file is created for the "Read" events arriving from an Harp device. The resulting file name is not that helpful, since it only contains the name of the device and date. It would be helpful to add a small string to the file name to identify the type of data it contains. E.g.:

HarpData_Read_1904-02-10T04-00-00.bin
HarpData_Dump_1904-02-10T04-00-00.bin

It might break the convention of having an _int_ after the device name, however the current filename already breaks such convetion.

**Comment by glopesdev** [comment]
@jkbhagatio @bruno-f-cruz The current assumption is there are no `Read` commands during the task acquisition, so the only read messages you will ever see are the ones from the initial dump.

If we drop that assumption, then currently there is no good way in the Harp protocol of separating what is a "register dump" from replies to other normal `Read` requests which may happen while the workflow is running. We can introduce a timer but that's always risky.
