### ISSUE TITLE
Release acquisition package

### ISSUE THREAD

**Issue by glopesdev** [SainsburyWellcomeCentre/aeon_acquisition#106]
Now that Bonsai 2.7 is released I think we are ready to commit to releasing a first stable version of the Aeon acquisition package. The final step is mostly deciding when and where to release (i.e. where do we host / release it: publicly in NuGet, GitHub or Bonsai-Boost/Community).

**Comment by glopesdev** [comment]
@jkbhagatio @Dario55 @bruno-f-cruz @aspaNeuro Maybe we can discuss this during the task control meeting on Wednesday?

**Comment by jkbhagatio** [comment]
Are we good to release this? @Dario55 @glopesdev
