### ISSUE TITLE
Basler hardware frame counters cannot be trusted to accurately detect hardware frame drops

### ISSUE THREAD

**Issue by glopesdev** [SainsburyWellcomeCentre/aeon_acquisition#107]
Harp trigger timestamps are paired with frames by using the `Zip` operator to combine each frame with each trigger, in order of arrival. This assumes there are no dropped frames.

To protect the pairing of Harp triggers with grabbed frames in the presence of spurious accidental frame drops, we have code in place to compute the difference in hardware frame counters across two grabbed frames. If the frame counter difference is greater than one frame, we will pad the video sequence with `null` frames to ensure that the pairing can still be done in order.

https://github.com/SainsburyWellcomeCentre/aeon_acquisition/blob/c13d7d8bb9becda6a67d4a763d840fe09a64b234/src/Aeon.Acquisition/PylonCapture.cs#L22

However, while running CPU performance benchmarks for closed-loop latency, we identified a strange behavior in the timestamp of video frames after such a frame drop correction. Specifically, we observed that even though `null` frames were generated for drops detected with the hardware frame counter, the adjusted timestamp had a significant difference to the latest live "real-time" trigger timestamp.

<img width="919" alt="missed hardware frame drops" src="https://user-images.githubusercontent.com/5315880/207913354-58532328-765d-4231-8e44-6da8a85cada0.png">

On further investigation, we discovered that differences in hardware frame counters can sometimes be smaller than differences in the hardware timestamp across two frames. One possible explanation for this would be if the frame drops are due to a faulty USB connection which forces the camera microcontroller to reset the connection. If during this recovery procedure the microcontroller ignores trigger TTLs coming from the Harp device, those triggers would not be able to initiate a new exposure at the hardware level, and thus the hardware frame counter would not be incremented.

We prototyped a new strategy for correcting hardware frame drops based on hardware timestamp differences, which as expected did solve the issue:

```c#
.FillGaps(frame => frame.ChunkData.Timestamp, (previous, current) => (int)Math.Round((current - previous - frameInterval) / frameInterval))
```

<img width="861" alt="corrected hardware frame drops" src="https://user-images.githubusercontent.com/5315880/207913568-a2642048-d0c5-4bf2-b8d6-eec8174e96ae.png">

We now need to develop this approach further to validate the numerical calculations against possible edge cases such as clock wraparound, etc. We also need to automatically extract the expected camera trigger frequency to compute the ideal frame interval. We are currently not sure if this is a Basler specific behavior since we have not yet observed this in the FLIR cameras, so for now we will modify only the Basler acquisition.

**Comment by glopesdev** [comment]
After further testing, this issue does indeed seem to be specific to highly degenerate hardware configurations where the integrity of the USB communication between the camera and the computer is compromised, to the point where the camera firmware starts to ignore electrical triggers.

When this happens it is a permanent condition, and the problem will promptly manifest usually under a minute after starting the workflow. It is also non-transient, meaning it will constantly reoccur as long as the workflow is running and compromise the integrity of all the collected data from the affected camera.

On the other hand, in non-degenerate situations, we always get correct frame drop reporting and the existing recovery mechanisms are appropriate, and the issue might be transient.

Given the above our current approach is to assume that this is a non-recoverable error that requires prompt intervention. We do not want to try to pad the sequence based on hardware-timestamps and start masking out a transmission problem which is fundamentally irrecoverable. Our approach to this issue will be to track it as part of the online quality control system and report it as a critical alert if it ever happens.

**Comment by jkbhagatio** [comment]
Closing as I think resolved, feel free to re-open if not
